#%RAML 1.0
title: Humanity
version: v1
baseUri: https://api.github.com
uses:
  ramltojaxrs: ramltojaxrs.raml

types:
    Network:
        (ramltojaxrs.types):
            plugins:
              - name: myown.deprecate
        type: object
        properties:
            name:
                required: true
                type: string
            dns-address:
                required: true
                type: string
    Switch:
        (ramltojaxrs.types):
            plugins:
              - name: core.suppressType
        type: object
        properties:
            portcount:
                required: true
                type: integer

    ChainableRouter:
        (ramltojaxrs.types):
            plugins:
              - name: myown.chain
        type: object
        properties:
            portCount:
                required: true
                type: integer
            routerName:
                required: true
                type: string
