#%RAML 1.0
title: Humanity
version: v1
baseUri: https://api.github.com
uses:
  LibraryOne: types.raml

/animals:
    get:
        queryParameters:
            type: string
        responses:
            200:
                body:
                    application/xml:
                        type: LibraryOne.Animal[]
    /{id}:
        uriParameters:
            id: string
        get:
            responses:
                200:
                    body:
                        application/xml:
                            type: LibraryOne.Animal
        put:
            body:
                application/xml:
                    type: LibraryOne.Animal
            responses:
                200:
