#%RAML 1.0
title: Humanity
version: v1
baseUri: https://api.github.com
uses:
  LibraryOne: types.raml
types:
    Gaaaakh: |
        {
          "type": "object",
          "$schema": "http://json-schema.org/draft-04/schema#",
          "id": "urn:jsonschema:com:zzzzz:advisor:domain:entities:Model",
          "additionalProperties": false,
          "properties": {
          "pageNumber": {
          "type": "integer"
          },
          "pageSize": {
          "type": "integer"
          },
          "numberOfPages": {
          "type": "integer"
          },
          "totalNumberOfElements": {
          "type": "integer"
          },
          "page": {
          "type": "array",
          "items": {
          "$schema": "model.res.json"
          }
          }
          }
        }

/animals:
    get:
        queryParameters:
            type: string
        responses:
            200:
                body:
                    application/xml:
                        type: LibraryOne.Animal[]
    /{id}:
        uriParameters:
            id: string
        get:
            responses:
                200:
                    body:
                        application/xml:
                            type: LibraryOne.Animal
        put:
            body:
                application/xml:
                    type: LibraryOne.Animal
            responses:
                200:
