#%RAML 1.0 Library
annotationTypes:
    types:
        allowedTargets: TypeDeclaration
        properties:
            className?:
                type: string
            implementationClassName?:
                type: string
            usePrimitiveType?:
                type: boolean
            abstract?:
                type: boolean
    resources:
        allowedTargets: Resource
        properties:
            onResourceClassCreation?: string
            onResourceClassFinish?: string
    methods:
        allowedTargets: Method
        properties:
            onMethodCreation?: string
            onMethodFinish?: string
            onResponseClassCreation?: string
            onResponseClassFinish?: string
    responses:
        allowedTargets: Method
        properties:

