#%RAML 1.0 Library
annotationTypes:
    types:
        allowedTargets: [TypeDeclaration,API]
        type: array
        items:
            properties:
                name: string
                arguments?: string[]