#%RAML 1.0 Library
annotationTypes:
    types:
        allowedTargets: [TypeDeclaration,API]
        properties:
            className?:
                type: string
            implementationClassName?:
                type: string
            usePrimitiveType?:
                type: boolean
            abstract?:
                type: boolean
            plugins?: any[]