#%RAML 1.0
title: Humanity
version: v1
baseUri: https://api.github.com
uses:
  ramltojaxrs: ramltojaxrs.raml

types:

    Gender:
        enum: [male, female, other]
    Leg:
        properties:
            toes: integer
    Arm:
        properties:
            fingers: integer
    Limb:
        Arm | Leg
    Person:
        type: Human
        discriminatorValue: person
        properties:
            name:
                required: true
                type: string
            weight:
                required: true
                type: integer
            siblings:
                type: Human[]
    Corpse:
        type: Human
        discriminatorValue: corpse
        properties:
            dateOfDeath:
                required: true
                type: date-only
    Human:
        type: object
        (ramltojaxrs.types):
            abstract: true
        discriminator: humanType
        properties:
            humanType: string
            limbs: Limb
            timeOfArrival: datetime-only
            timeOfBirth: time-only
            dateOfBirth: date-only
            instantOfBirth: datetime
            requestTime:
                type: datetime
                format: rfc2616
            gender:
                type: Gender
/humanity:
    (ramltojaxrs.resources):
        onResourceClassCreation: org.raml.jaxrs.generator.builders.extensions.resources.TrialResourceExtension
    get:
        (ramltojaxrs.methods):
            onResourceMethodCreation: org.raml.jaxrs.generator.builders.extensions.resources.TrialResourceMethodExtension
            onResponseClassCreation: org.raml.jaxrs.generator.builders.extensions.resources.TrialResponseClassExtension
        queryParameters:
            type: string
        responses:
            200:
                (ramltojaxrs.responses):
                    onResponseMethodCreation: org.raml.jaxrs.generator.builders.extensions.resources.TrialResponseMethodExtension
                body:
                    application/json:
                        type: Human
    put:
        body:
            application/json:
                type: Human
        responses:
            200:
