#%RAML 1.0
title: Humanity
version: v1
baseUri: https://api.github.com
uses:
  ramltojaxrs: ramltojaxrs.raml
(ramltojaxrs.types):
  onTypeCreation: [ core.suppress-additional-properties ]
types:
#    ObjectOne:
#        type: object
#        properties:
#            name:
#                type: object
#                description: yes!!
    HumanId:
        properties:
            serial: string
            type: string

    Gender:
        enum: [male, female, other]
    Leg:
      properties:
          toes: integer
    Arm:
        properties:
            fingers: integer
    Limb:
        Arm | Leg
    Person:
        type: Human
        discriminatorValue: person
        properties:
            name:
                required: true
                type: string
            weight:
                required: true
                type: integer
            siblings:
                type: Human[]
    Corpse:
        type: Human
        discriminatorValue: corpse
        properties:
            dateOfDeath:
                required: true
                type: date-only
    Human:
        type: object
        discriminator: humanType
        discriminatorValue: human
        properties:
            humanType: string
            limbs: Limb
            timeOfArrival: datetime-only
            timeOfBirth: time-only
            dateOfBirth: date-only
            instantOfBirth: datetime
            requestTime:
                type: datetime
                format: rfc2616
            actualGender:
                type: Gender

/complexhumans:
    description: Hello!!!
    get:
        (ramltojaxrs.methods):
            onResourceMethodCreation: [ org.raml.jaxrs.generator.builders.extensions.resources.TrialResourceMethodExtension ]
            onResponseClassCreation: [ org.raml.jaxrs.generator.builders.extensions.resources.TrialResponseClassExtension ]
        queryParameters:
            id: HumanId
        responses:
            200:
                (ramltojaxrs.responses):
                    onResponseMethodCreation: [ org.raml.jaxrs.generator.builders.extensions.resources.TrialResponseMethodExtension ]
                body:
                    application/json:
                        type: Human
    /{id}:
        uriParameters:
            id: HumanId
        get:
            (ramltojaxrs.methods):
                onResourceMethodCreation: [ org.raml.jaxrs.generator.builders.extensions.resources.TrialResourceMethodExtension ]
                onResponseClassCreation: [ org.raml.jaxrs.generator.builders.extensions.resources.TrialResponseClassExtension ]
            responses:
                200:
                    (ramltojaxrs.responses):
                        onResponseMethodCreation: [ org.raml.jaxrs.generator.builders.extensions.resources.TrialResponseMethodExtension ]
                    body:
                        application/json:
                            type: Human

/humans:
    get:
        (ramltojaxrs.methods):
            onResourceMethodCreation: [ org.raml.jaxrs.generator.builders.extensions.resources.TrialResourceMethodExtension ]
            onResponseClassCreation: [ org.raml.jaxrs.generator.builders.extensions.resources.TrialResponseClassExtension ]
        queryParameters:
            type: string
        responses:
            200:
                (ramltojaxrs.responses):
                    onResponseMethodCreation: [ org.raml.jaxrs.generator.builders.extensions.resources.TrialResponseMethodExtension ]
                body:
                    application/json:
                        type: Human[]
                headers:
                  boo:
                  somethingElse:
    /{id}:
        uriParameters:
            id: string
        get:
            queryParameters:
                type: string
            responses:
                200:
                    (ramltojaxrs.responses):
                        onResponseMethodCreation: [ org.raml.jaxrs.generator.builders.extensions.resources.TrialResponseMethodExtension ]
                    body:
                        application/json:
                            type: Human
        put:
            body:
                application/json:
                    type: Human
            responses:
                200:
                  headers:
                    someOtherHeader:
