#%RAML 1.0
title: GitHub API
version: v3
baseUri: https://api.github.com
mediaType:
 - application/json
 - application/xml
traits:
resourceTypes:
 basicType:
  get:
  put:
  post:
/search:
  description: The search resource
  type: basicType
  get:
   queryParameters:
    hello_dude: string
    fink: number
  /code:
    get:
     queryParameters:
       hello_man: string
       fink: number
