#%RAML 1.0
title: Tracks
version: v1
baseUri: https://api.github.com
mediaType: application/json
types:
    Track:
        schema: |
         {
           "type": "object",
           "$schema": "http://json-schema.org/draft-03/schema",
           "id": "http://jsonschema.net",
           "required": true,
           "properties": {
             "songTitle": {
               "type": "string",
               "required": true
             },
             "albumId": {
               "type": "string",
               "required": true,
               "minLength": 36,
               "maxLength": 36
             }
           }
         }

/tracks:
    description: The search resource
    get:
        responses:
            200:
                body:
                    application/json:
                        type: Track
    put:
        body:
            application/json:
                type: Track
