#%RAML 1.0
title: Cars
version: v1
baseUri: https://api.github.com
types:
    Car:
        type: object
        properties:
            make:
                required: true
                type: string
            number:
                required: true
                type: integer

/inventory:
    description: The search resource
    get:
        responses:
            200:
                body:
                    application/json:
                        type: Car
    put:
        body:
            text/plain:
                type: Car
