#%RAML 1.0 Library
annotationTypes:
    types:
        allowedTargets: TypeDeclaration
        properties:
            className?:
                type: string
            usePrimitiveType?:
                type: boolean
            abstract?:
                type: boolean
