#%RAML 1.0
title: Humanity
version: v1
baseUri: https://api.github.com
types:
    Person:
        type: Human
        discriminatorValue: person
        properties:
            name:
                required: true
                type: string
            weight:
                required: true
                type: integer
    Corpse:
        type: Human
        discriminatorValue: corpse
        properties:
            dateOfDeath:
                required: true
                type: date-only
    Human:
        type: object
        discriminator: humanType
        properties:
            humanType: string
            male:
                type: boolean
/humanity:
    get:
        queryParameters:
            type: string
        responses:
            200:
                body:
                    application/json:
                        type: Human
    put:
        body:
            application/json:
                type: Human
        responses:
            200:
