#%RAML 1.0
title: Humanity
version: v1
baseUri: https://api.github.com
types:
    Person:
        type: Human
        properties:
            name:
                required: true
                type: string
            weight:
                required: true
                type: integer
    Human:
        type: object
        properties:
            male:
                type: boolean
