#%RAML 1.0
title: Humanity
version: v1
baseUri: https://api.github.com
uses:
  ramltojaxrs: ramltojaxrs.raml
  ramltopojo: ramltopojo.raml
types:
  User:
    properties:
      name: string
/multipart:
     post:
        body:
            multipart/form-data:
                type: object
                properties:
                    appBundle:
                        type:
                            type: file
                    configFile:
                        type:
                            type: file
                    consumed:
                        type: User
                    heyBool:
                      type: boolean
                displayName:
                    value: "multipart/form-data"

