#%RAML 1.0
title: Humanity
version: v1
baseUri: https://api.github.com

types:
    Gender:
        enum: [male, female, other]
    Animal:
        type: object
        properties:
            animalType:
                type: string
            specimenName:
                type: string
                xml:
                    attribute: true
                    namespace: "foo.bar"
            gender:
                type: Gender
            siblings:
                type: Animal[]
                xml:
                    wrapped: true
            mother:
                type: Animal
            ancestor:
                type: Ancestor
    Insect:
        type: Animal
        properties:
            icky:
                type: boolean
    Invertebrate:
        type: Animal
        properties:
            squishy:
                type: boolean
    Ancestor:
        type: Insect | Invertebrate

/animals:
    get:
        queryParameters:
            type: string
        responses:
            200:
                body:
                    application/xml:
                        type: Animal[]
    /{id}:
        uriParameters:
            id: string
        get:
            responses:
                200:
                    body:
                        application/xml:
                            type: Animal
        put:
            body:
                application/xml:
                    type: Animal
            responses:
                200:
