#%RAML 1.0
title: who cares
types:
    TypeOne:
        type: object
        properties:
            day: ReturnValue[]
    ReturnValue:
        type: object
        properties:
            whocares: boolean
