#%RAML 1.0
title: who cares
types:
    TypeOne:
        properties:
            day:
                type: string
                enum: [ "monday", "friday" ]

    TypeTwo:
        type: string
        enum: [ "either", "or" ]
