#%RAML 1.0
title: who cares
types:
    ObjectBase:
        type: object
        properties:
            time: string
    ObjectOne:
        properties:
            name:
                type: ObjectBase
