#%RAML 1.0
title: Tracks
version: v1
baseUri: https://api.github.com
mediaType: application/json
/tracks:
    description: The search resource
    get:
        responses:
            200:
                body:
                    application/json:
